# Generated by Django 6.0.4 on 2026-04-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='000000000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
