# Generated by Django 6.0.4 on 2026-04-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motoqueiroprofile',
            name='stock_count',
        ),
        migrations.AddField(
            model_name='motoqueiroprofile',
            name='empresa',
            field=models.CharField(default='Independente', max_length=100),
        ),
        migrations.AddField(
            model_name='motoqueiroprofile',
            name='stock_canata',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motoqueiroprofile',
            name='stock_sonangol',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
