# Generated by Django 6.0.4 on 2026-04-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EM_ESPERA', 'Em Espera'), ('ATRIBUIDO', 'Atribuído'), ('A_CAMINHO', 'A Caminho'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='EM_ESPERA', max_length=20)),
                ('delivery_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_address', models.TextField()),
                ('pin_code', models.CharField(editable=False, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
